### ISSUE TITLE
Issue compiling vulkan branch -- manjaro

### ISSUE THREAD

**Issue by tree786isback** [krait-games/hyperion-engine#23]
Hey,

I've tried to compile the `vulkan` branch on manjaro, but I get lots of errors:
```c++
src/asset/fbom/../../util/string_util.h: In static member function ‘static constexpr std::string hyperion::StringUtil::ToLower(const string&)’:
src/asset/fbom/../../util/string_util.h:18:21: error: variable ‘result’ of non-literal type ‘std::string’ {aka ‘std::__cxx11::basic_string<char>’} in ‘constexpr’ function
   18 |         std::string result(str);
      |                     ^~~~~~
In file included from /usr/include/c++/11.2.0/string:55,
                 from src/asset/fbom/../../hash_code.h:6,
                 from src/asset/fbom/type.h:4,
                 from src/asset/fbom/type.cpp:1:
/usr/include/c++/11.2.0/bits/basic_string.h:85:11: note: ‘std::__cxx11::basic_string<char>’ is not literal because:
   85 |     class basic_string
      |           ^~~~~~~~~~~~
/usr/include/c++/11.2.0/bits/basic_string.h:85:11: note:   ‘std::__cxx11::basic_string<char>’ does not have ‘constexpr’ destructor
In file included from src/asset/fbom/../../util.h:4,
                 from src/asset/fbom/base_types.h:5,
                 from src/asset/fbom/type.cpp:2:
src/asset/fbom/../../util/string_util.h:20:23: error: no matching function for call to ‘transform(std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, std::__cxx11::basic_string<char>::iterator, <unresolved overloaded function type>)’
   20 |         std::transform(result.begin(), result.end(), result.begin(), std::tolower);
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11.2.0/vector:62,
                 from /usr/include/c++/11.2.0/functional:62,
                 from src/asset/fbom/../../hash_code.h:5,
                 from src/asset/fbom/type.h:4,
                 from src/asset/fbom/type.cpp:1:
/usr/include/c++/11.2.0/bits/stl_algo.h:4285:5: note: candidate: ‘template<class _IIter, class _OIter, class _UnaryOperation> constexpr _OIter std::transform(_IIter, _IIter, _OIter, _UnaryOperation)’
 4285 |     transform(_InputIterator __first, _InputIterator __last,
      |     ^~~~~~~~~
/usr/include/c++/11.2.0/bits/stl_algo.h:4285:5: note:   template argument deduction/substitution failed:
In file included from src/asset/fbom/../../util.h:4,
                 from src/asset/fbom/base_types.h:5,
                 from src/asset/fbom/type.cpp:2:
src/asset/fbom/../../util/string_util.h:20:23: note:   couldn’t deduce template parameter ‘_UnaryOperation’
   20 |         std::transform(result.begin(), result.end(), result.begin(), std::tolower);
      |         ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11.2.0/vector:62,
                 from /usr/include/c++/11.2.0/functional:62,
                 from src/asset/fbom/../../hash_code.h:5,
                 from src/asset/fbom/type.h:4,
                 from src/asset/fbom/type.cpp:1:


```
Any ideas what the issue might be?
FYI I using GCC v11 compiler on xfce manjaro

**Comment by tree786isback** [comment]
@ajmd17 Do you happen to know if this compiles on arch based distros?

**Comment by ajmd17** [comment]
Hey, we've definitely had it compiling on manjario but I'm not sure we've tried it with gcc recently, only clang and msvc. It looks like the constexpr qualifier could be removed from those methods, and that could make it work...

I'll say that the vulkan branch is changing pretty rapidly so this type of breaking feature is bound to come up under different environments, for now

**Comment by tree786isback** [comment]
Ok I see, thanks for clarifying. Do you have a rough idea when the vulkan branch might get reasonable stability (in terms of stable-ish API)? I'd like to start using it, but not sure how long I should wait (or if I should try the deprecated OpenGL one first)?

**Comment by tree786isback** [comment]
@ajmd17 I've hacked at some sources files and forced it to compile on manjaro. But when I run the binary, I get a strange pink rectangle which moves up and down:
![Peek 2022-05-02 14-55](https://user-images.githubusercontent.com/97201835/166246124-2afb5492-2736-4b77-91ab-cd481e925003.gif)

Is that supposed to be how it looks?

**Comment by ajmd17** [comment]
Something is definitely off, are there many messages from validation layers in your console?

We're rendering in that corner as a test for compute shaders.

We've had this running on manjaro on an rtx 3060. What graphics card are you running on?

**Comment by ajmd17** [comment]
@tree786isback I *may* have some insight into whats causing this. There is a commit that should be in the `vulkan` branch but may only exist in `vulkan-rtx` that I'll need to cherry-pick over. @emd22 was having a different issue, but on manjaro the ssao shader caused a crash when the # of samples was an even number (no idea...)

**Comment by tree786isback** [comment]
> Something is definitely off, are there many messages from validation layers in your console?

Hmm here is the terminal output:
[out.log.zip](https://github.com/krait-games/hyperion-engine/files/8605972/out.log.zip)

>We've had this running on manjaro on an rtx 3060. What graphics card are you running on?

Ah yeah, I have a much much older graphics card GTX 760 from 2013! That's probably why then

**Comment by tree786isback** [comment]
> I _may_ have some insight into whats causing this. There is a commit that should be in the `vulkan` branch but may only exist in `vulkan-rtx` that I'll need to cherry-pick over. @emd22 was having a different issue, but on manjaro the ssao shader caused a crash when the # of samples was an even number (no idea...)

Alright, is the vulkan branch of hyperion aimed mainly at rtx cards? I think it'll probably not work in that case with my old graphics hardware

**Comment by ajmd17** [comment]
We're aiming to support non-rtx cards as well! As long as Vulkan 1.2 is supported (along with a few widely supported extensions) it should be fine. The rtx stuff itself will be something that can be enabled.

I pushed the SSAO fix to `vulkan`. It may fix the issues you were having, it may not. I'll take a look at your log output and see what I can find. thanks for sending that!

**Comment by ajmd17** [comment]
Just for reference, in that branch, what you should see is this:
(There is also a transparent zombie guy there with a spinning head... Testing transparency and mesh skinning!)

![image](https://user-images.githubusercontent.com/9222202/166327384-26c0ed53-7298-4b3a-a0bd-eab58bff6262.png)

**Comment by tree786isback** [comment]
>I pushed the SSAO fix to vulkan. It may fix the issues you were having, it may not. I'll take a look at your log output and see what I can find. thanks for sending that!

Sweet, thanks for that! I'll try and compile with the latest commit and let you know of the outcome!

**Comment by ajmd17** [comment]
Awesome! thanks!
I have a second suspicion (not having a dedicated compute queue). That shouldn't be an issue but I don't have any way to test at the moment. 
I'm going to turn off the imagestore test (thing in the right) and push that, we'll see if something doesn't make this thing work.

**Comment by ajmd17** [comment]
That's pushed, if you want to try that out.

**Comment by tree786isback** [comment]
Hm I'm trying to compile, but now I'm getting many new errors which didn't seem to happen before, like this:
```c++
src/rendering/backend/renderer_image.cpp:330:71: error: too many arguments provided to function-like macro invocation
        HYPERION_BUBBLE_ERRORS(staging_buffer.Create(device, m_size), result);
```
Not too sure how to fix it, as I'm not familiar with the code base. For some reason this error didn't show up when I tried to compile a few days ago. Not too sure if I checked out the wrong branch back then or something.

**Comment by ajmd17** [comment]
Oh, this is a pesky mistake that keeps popping up. It's been fixed in various branches but for some reason got carried over. Msvc allows having more arguments provided to a macro for some reason..

I'm not at my computer at the moment so I can't push the fix, but if you wanted to just remove `, result` from the end of that line in renderer_image.cpp, it should work.

**Comment by tree786isback** [comment]
Ah yeah, that seem to have fixed that issue now, cheers! But I'm also getting another error as well, related to `MathUtil::Min`:
```c++
src/rendering/backend/renderer_buffer.cpp:602:33: error: no matching function for call to 'Min'
            const size_t dist = MathUtil::Min(data.size() - i, 4ull);
                                ^~~~~~~~~~~~~
```
I haven't investigated why it's throwing an error yet

**Comment by ajmd17** [comment]
Should be fixed now, was just missing an include for `<math/math_util.h>`. I wish these compiler errors were more consistent!

**Comment by tree786isback** [comment]
Alright much better now!
![Peek 2022-05-04 14-40](https://user-images.githubusercontent.com/97201835/166693400-b7d25954-a1df-4a8d-8d85-659fb764388e.gif)

I've had comment out some stuff, and delete others to force it to compile, as it still compiled about things like `MathUtil::Min`. I basically deleted that part, and deleted some constexpr's and commented out the `std::transform` parts in `string_util.h`. BTW I'm using clang (not GCC atm, although eventually I want to try and get it compiling with GCC)

**Comment by tree786isback** [comment]
FYI here are the errors I get if try and compile the plain vulkan branch:
```c++

src/rendering/backend/renderer_buffer.cpp:601:33: error: no matching function for call to 'Min'
            const size_t dist = MathUtil::Min(data.size() - i, 4ull);
                                ^~~~~~~~~~~~~
src/math/math_util.h:97:31: note: candidate template ignored: deduced conflicting types for parameter 'T' ('unsigned long' vs. 'unsigned long long')
    static inline constexpr T Min(const T &a, const T &b)
```

And also :
```c++
src/util/string_util.h:20:9: error: no matching function for call to 'transform'
        std::transform(result.begin(), result.end(), result.begin(), std::tolower);
        ^~~~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-pc-linux-/11.2.0/../../../../include/c++/11.2.0/bits/stl_algo.h:4285:5: note: candidate template ignored: couldn't infer template argument '_UnaryOperation'
    transform(_InputIterator __first, _InputIterator __last,
    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-/11.2.0/../../../../include/c++/11.2.0/bits/stl_algo.h:4323:5: note: candidate function template not viable: requires 5 arguments, but 4 were provided
    transform(_InputIterator1 __first1, _InputIterator1 __last1,
    ^
/usr/bin/../lib64/gcc/x86_64-pc-linux-/11.2.0/../../../../include/c++/11.2.0/pstl/glue_algorithm_defs.h:156:1: note: candidate function template not viable: requires 5 arguments, but 4 were provided
transform(_ExecutionPolicy&& __exec, _ForwardIterator1 __first, _ForwardIterator1 __last, _ForwardIterator2 __result,
```  

I've basically had to delete those parts and comment some others out to allow a successful compile with clang, so it will probably cause some other issues down the road if I try and use any of those functions

**Comment by ajmd17** [comment]
Happy to see it's getting somewhere! Odd that the material sphere has no color but this is a start :)

If you want to submit a PR with your changes id love to take a look at what you had to do to get it working for you! Don't worry if it's hacky or anything, I don't mind fixing anything up.

For those compiler errors:
1) it seems like `data.size() - i` is `unsigned long`, when it is expected to be `unsigned long long`. This seems to be because you're compiling for x86 and `size_t` is not necessarily defined as `unsigned long long`. We could fix this by changing `4ull` to `size_t(4)`

2) looks like it's missing in include for `<algorithm>`?

3) seems to be the same sort of issue we were having above. We'll have to take the constexpr qualifier off that, it looks like. No big issue but it's odd that this behaves differently in different compilers

**Comment by ajmd17** [comment]
Ah, now I remember, @emd22 had the same issue with `std::transform`. He had to wrap `tolower` in a lambda.
So like this:

`[](char ch) { return std::to lower(ch); }`

**Comment by tree786isback** [comment]
> Ah, now I remember, @emd22 had the same issue with `std::transform`. He had to wrap `tolower` in a lambda. So like this:
> 
> `[](char ch) { return std::tolower(ch); }`

Ah that solved it! It now renders correctly
![Peek 2022-05-04 17-58](https://user-images.githubusercontent.com/97201835/166739677-bbf16289-d311-4406-89e6-97eac3db9c27.gif)

I think it was black previously because I commented out the `std::transform` part to allow it to compile. Turns out that was a core component to the renderer!

**Comment by ajmd17** [comment]
> > Ah, now I remember, @emd22 had the same issue with `std::transform`. He had to wrap `tolower` in a lambda. So like this:
> > `[](char ch) { return std::tolower(ch); }`
> 
> Ah that solved it! It now renders correctly ![Peek 2022-05-04 17-58](https://user-images.githubusercontent.com/97201835/166739677-bbf16289-d311-4406-89e6-97eac3db9c27.gif)
> 
> I think it was black previously because I commented out the `std::transform` part to allow it to compile. Turns out that was a core component to the renderer! Many thanks for the help!

And thanks for debugging, I'm glad it works now!

**Comment by tree786isback** [comment]
Thanks! As a side question, do you happen to know when the API for hyperion will become more or less fixed? I was planning on potentially porting over some OpenGL projects (using other rendering frameworks that I've been using previously), but not sure if I should wait until the API becomes relatively stable?

**Comment by ajmd17** [comment]
I'm in the process of cleaning some stuff up now so that it should be easier to get started. We'll have to remove a good chunk of the old stuff because it was rewritten, and some things haven't been reimplemented to work with the new stuff, so some pieces will be missing. in general though, you shouldn't face any huge breaking API changes. Just know that we're building stuff but we are moving pretty quickly with it :)

**Comment by ajmd17** [comment]
This weekend I'll have a chance to move all the new stuff out of a folder and into the root and clean it up. 

I have a branch that has a Game class and everything to get started running a game thread. Maybe after this weekend it'll be ready, but I can let you know here

**Comment by tree786isback** [comment]
Nice, thanks for the info! I noticed the `main.cpp` contains a fair bit of lower-level vulkan code, is that going to stay, or is it part of the old block of code which will be removed? Looking forward to checking the Game class out!

**Comment by ajmd17** [comment]
That will all be removed or moved into somewhere less intrusive. It was only there for testing stuff anyway haha

**Comment by tree786isback** [comment]
Cool! I plan on porting a personal raycasted vehicle project to use hyperion.
![Peek 2022-05-06 15-57](https://user-images.githubusercontent.com/97201835/167159049-07c1af8d-dc3d-474f-bfe3-691bd4bc926c.gif)
[simplescreenrecorder-2022-05-02_19.36.21.m4v.zip](https://github.com/krait-games/hyperion-engine/files/8641620/simplescreenrecorder-2022-05-02_19.36.21.m4v.zip)

Currently it uses opengl, but the framework I'm using lacks good support for alpha materials and shaders in general. Look forward to porting it to hyperion and hopefully making use of some foliage shaders and other neat features!

**Comment by emd22** [comment]
Hey, want to join the krait games discord? 
[https://discord.gg/yuHgrcu3](url)

**Comment by tree786isback** [comment]
> https://discord.gg/yuHgrcu3

Thanks!
