### ISSUE TITLE
Hi There, please delete this issue, I asked for rendering papers but you don't answer, now I can not delete this issue by myself. Please delete it so it will not appear on my github, thank you!

### ISSUE THREAD

**Issue by AlerianEmperor** [krait-games/hyperion-engine#48]

**Comment by ajmd17** [comment]
Closed it now, apologies, really I can not share most papers as some of it comes from personal experience just reading articles online over the years as well as things I've learned on the job.
I'd recommend checking out Morgan McGuire's papers
